// Code generated by go-swagger; DO NOT EDIT.

package invite

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/racoon-devel/calendar/internal/server/models"
)

// GetInvitesHandlerFunc turns a function with the right signature into a get invites handler
type GetInvitesHandlerFunc func(GetInvitesParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetInvitesHandlerFunc) Handle(params GetInvitesParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetInvitesHandler interface for that can handle valid get invites params
type GetInvitesHandler interface {
	Handle(GetInvitesParams, *models.Principal) middleware.Responder
}

// NewGetInvites creates a new http.Handler for the get invites operation
func NewGetInvites(ctx *middleware.Context, handler GetInvitesHandler) *GetInvites {
	return &GetInvites{Context: ctx, Handler: handler}
}

/*
	GetInvites swagger:route GET /invite invite getInvites

Получить информацию о приглашениях для текущего пользователя
*/
type GetInvites struct {
	Context *middleware.Context
	Handler GetInvitesHandler
}

func (o *GetInvites) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetInvitesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
