// Code generated by go-swagger; DO NOT EDIT.

package invite

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetInvitesHandlerFunc turns a function with the right signature into a get invites handler
type GetInvitesHandlerFunc func(GetInvitesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetInvitesHandlerFunc) Handle(params GetInvitesParams) middleware.Responder {
	return fn(params)
}

// GetInvitesHandler interface for that can handle valid get invites params
type GetInvitesHandler interface {
	Handle(GetInvitesParams) middleware.Responder
}

// NewGetInvites creates a new http.Handler for the get invites operation
func NewGetInvites(ctx *middleware.Context, handler GetInvitesHandler) *GetInvites {
	return &GetInvites{Context: ctx, Handler: handler}
}

/*
	GetInvites swagger:route GET /invite invite getInvites

Получить информацию о приглашениях для текущего пользователя
*/
type GetInvites struct {
	Context *middleware.Context
	Handler GetInvitesHandler
}

func (o *GetInvites) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetInvitesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
