// Code generated by go-swagger; DO NOT EDIT.

package invite

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/racoon-devel/calendar/internal/server/models"
)

// GetInvitesOKCode is the HTTP code returned for type GetInvitesOK
const GetInvitesOKCode int = 200

/*
GetInvitesOK Список приглашений

swagger:response getInvitesOK
*/
type GetInvitesOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetInvitesResponse `json:"body,omitempty"`
}

// NewGetInvitesOK creates GetInvitesOK with default headers values
func NewGetInvitesOK() *GetInvitesOK {

	return &GetInvitesOK{}
}

// WithPayload adds the payload to the get invites o k response
func (o *GetInvitesOK) WithPayload(payload *models.GetInvitesResponse) *GetInvitesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get invites o k response
func (o *GetInvitesOK) SetPayload(payload *models.GetInvitesResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInvitesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetInvitesInternalServerErrorCode is the HTTP code returned for type GetInvitesInternalServerError
const GetInvitesInternalServerErrorCode int = 500

/*
GetInvitesInternalServerError Ошибка на стороне сервера

swagger:response getInvitesInternalServerError
*/
type GetInvitesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload models.Dummy `json:"body,omitempty"`
}

// NewGetInvitesInternalServerError creates GetInvitesInternalServerError with default headers values
func NewGetInvitesInternalServerError() *GetInvitesInternalServerError {

	return &GetInvitesInternalServerError{}
}

// WithPayload adds the payload to the get invites internal server error response
func (o *GetInvitesInternalServerError) WithPayload(payload models.Dummy) *GetInvitesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get invites internal server error response
func (o *GetInvitesInternalServerError) SetPayload(payload models.Dummy) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInvitesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
