// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateMeetingErrorResponse create meeting error response
//
// swagger:model CreateMeetingErrorResponse
type CreateMeetingErrorResponse struct {

	// Код ошибки (700 - пользователь, создающий встречу занят в указанное время, 701 - неверный формат для RRULE, 702 - не найден приглашенный пользователь)
	// Required: true
	// Enum: [700 701 702]
	Code *int64 `json:"code"`
}

// Validate validates this create meeting error response
func (m *CreateMeetingErrorResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var createMeetingErrorResponseTypeCodePropEnum []interface{}

func init() {
	var res []int64
	if err := json.Unmarshal([]byte(`[700,701,702]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createMeetingErrorResponseTypeCodePropEnum = append(createMeetingErrorResponseTypeCodePropEnum, v)
	}
}

// prop value enum
func (m *CreateMeetingErrorResponse) validateCodeEnum(path, location string, value int64) error {
	if err := validate.EnumCase(path, location, value, createMeetingErrorResponseTypeCodePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CreateMeetingErrorResponse) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("code", "body", m.Code); err != nil {
		return err
	}

	// value enum
	if err := m.validateCodeEnum("code", "body", *m.Code); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create meeting error response based on context it is used
func (m *CreateMeetingErrorResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateMeetingErrorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateMeetingErrorResponse) UnmarshalBinary(b []byte) error {
	var res CreateMeetingErrorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
