// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateMeetingRequest create meeting request
//
// swagger:model CreateMeetingRequest
type CreateMeetingRequest struct {
	Meeting
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *CreateMeetingRequest) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Meeting
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Meeting = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m CreateMeetingRequest) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.Meeting)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this create meeting request
func (m *CreateMeetingRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this create meeting request based on the context it is used
func (m *CreateMeetingRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Meeting
	if err := m.Meeting.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
