// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetUsersError get users error
//
// swagger:model GetUsersError
type GetUsersError struct {

	// Код ошибки
	// 401 - требуется авторизация
	// 500 - ошибка на стороне сервера
	//
	// Required: true
	// Enum: [401 500]
	Code interface{} `json:"code"`

	// message
	Message *string `json:"message,omitempty"`
}

// Validate validates this get users error
func (m *GetUsersError) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var getUsersErrorTypeCodePropEnum []interface{}

func init() {
	var res []interface{}
	if err := json.Unmarshal([]byte(`[401,500]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getUsersErrorTypeCodePropEnum = append(getUsersErrorTypeCodePropEnum, v)
	}
}

// prop value enum
func (m *GetUsersError) validateCodeEnum(path, location string, value interface{}) error {
	if err := validate.EnumCase(path, location, value, getUsersErrorTypeCodePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GetUsersError) validateCode(formats strfmt.Registry) error {

	if m.Code == nil {
		return errors.Required("code", "body", nil)
	}

	return nil
}

// ContextValidate validates this get users error based on context it is used
func (m *GetUsersError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetUsersError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetUsersError) UnmarshalBinary(b []byte) error {
	var res GetUsersError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
