// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LoginError login error
//
// swagger:model LoginError
type LoginError struct {

	// Код ошибки
	// 403 - доступ запрещен
	// 500 - ошибка на стороне сервера
	//
	// Required: true
	// Enum: [403 500]
	Code interface{} `json:"code"`

	// Описание ошибки
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this login error
func (m *LoginError) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var loginErrorTypeCodePropEnum []interface{}

func init() {
	var res []interface{}
	if err := json.Unmarshal([]byte(`[403,500]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		loginErrorTypeCodePropEnum = append(loginErrorTypeCodePropEnum, v)
	}
}

// prop value enum
func (m *LoginError) validateCodeEnum(path, location string, value interface{}) error {
	if err := validate.EnumCase(path, location, value, loginErrorTypeCodePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *LoginError) validateCode(formats strfmt.Registry) error {

	if m.Code == nil {
		return errors.Required("code", "body", nil)
	}

	return nil
}

func (m *LoginError) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this login error based on context it is used
func (m *LoginError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LoginError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LoginError) UnmarshalBinary(b []byte) error {
	var res LoginError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
