// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewUser new user
//
// swagger:model NewUser
type NewUser struct {

	// Логин для входа в систему
	// Required: true
	// Max Length: 32
	// Min Length: 1
	Login *string `json:"login"`

	// Имя пользователя
	// Required: true
	// Min Length: 1
	Name *string `json:"name"`

	// Пароль
	// Required: true
	// Max Length: 32
	// Min Length: 8
	Password *string `json:"password"`

	// Фамилия пользователя
	// Required: true
	// Min Length: 1
	Surname *string `json:"surname"`
}

// Validate validates this new user
func (m *NewUser) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLogin(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSurname(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewUser) validateLogin(formats strfmt.Registry) error {

	if err := validate.Required("login", "body", m.Login); err != nil {
		return err
	}

	if err := validate.MinLength("login", "body", *m.Login, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("login", "body", *m.Login, 32); err != nil {
		return err
	}

	return nil
}

func (m *NewUser) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", *m.Name, 1); err != nil {
		return err
	}

	return nil
}

func (m *NewUser) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	if err := validate.MinLength("password", "body", *m.Password, 8); err != nil {
		return err
	}

	if err := validate.MaxLength("password", "body", *m.Password, 32); err != nil {
		return err
	}

	return nil
}

func (m *NewUser) validateSurname(formats strfmt.Registry) error {

	if err := validate.Required("surname", "body", m.Surname); err != nil {
		return err
	}

	if err := validate.MinLength("surname", "body", *m.Surname, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this new user based on context it is used
func (m *NewUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewUser) UnmarshalBinary(b []byte) error {
	var res NewUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
