// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserErrorResponse user error response
//
// swagger:model UserErrorResponse
type UserErrorResponse struct {

	// Код ошибки (700 - пользователь с таким логином уже существует)
	// Required: true
	// Enum: [700]
	Code *int64 `json:"code"`

	// Описание ошибки
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this user error response
func (m *UserErrorResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var userErrorResponseTypeCodePropEnum []interface{}

func init() {
	var res []int64
	if err := json.Unmarshal([]byte(`[700]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		userErrorResponseTypeCodePropEnum = append(userErrorResponseTypeCodePropEnum, v)
	}
}

// prop value enum
func (m *UserErrorResponse) validateCodeEnum(path, location string, value int64) error {
	if err := validate.EnumCase(path, location, value, userErrorResponseTypeCodePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *UserErrorResponse) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("code", "body", m.Code); err != nil {
		return err
	}

	// value enum
	if err := m.validateCodeEnum("code", "body", *m.Code); err != nil {
		return err
	}

	return nil
}

func (m *UserErrorResponse) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this user error response based on context it is used
func (m *UserErrorResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserErrorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserErrorResponse) UnmarshalBinary(b []byte) error {
	var res UserErrorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
