// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/racoon-devel/calendar/internal/server/models"
)

// PostUserLoginOKCode is the HTTP code returned for type PostUserLoginOK
const PostUserLoginOKCode int = 200

/*
PostUserLoginOK Вход выполнен успешно

swagger:response postUserLoginOK
*/
type PostUserLoginOK struct {

	/*
	  In: Body
	*/
	Payload *models.LoginResponse `json:"body,omitempty"`
}

// NewPostUserLoginOK creates PostUserLoginOK with default headers values
func NewPostUserLoginOK() *PostUserLoginOK {

	return &PostUserLoginOK{}
}

// WithPayload adds the payload to the post user login o k response
func (o *PostUserLoginOK) WithPayload(payload *models.LoginResponse) *PostUserLoginOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post user login o k response
func (o *PostUserLoginOK) SetPayload(payload *models.LoginResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUserLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUserLoginForbiddenCode is the HTTP code returned for type PostUserLoginForbidden
const PostUserLoginForbiddenCode int = 403

/*
PostUserLoginForbidden Доступ запрещен

swagger:response postUserLoginForbidden
*/
type PostUserLoginForbidden struct {

	/*
	  In: Body
	*/
	Payload models.Dummy `json:"body,omitempty"`
}

// NewPostUserLoginForbidden creates PostUserLoginForbidden with default headers values
func NewPostUserLoginForbidden() *PostUserLoginForbidden {

	return &PostUserLoginForbidden{}
}

// WithPayload adds the payload to the post user login forbidden response
func (o *PostUserLoginForbidden) WithPayload(payload models.Dummy) *PostUserLoginForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post user login forbidden response
func (o *PostUserLoginForbidden) SetPayload(payload models.Dummy) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUserLoginForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostUserLoginInternalServerErrorCode is the HTTP code returned for type PostUserLoginInternalServerError
const PostUserLoginInternalServerErrorCode int = 500

/*
PostUserLoginInternalServerError Ошибка на стороне сервера

swagger:response postUserLoginInternalServerError
*/
type PostUserLoginInternalServerError struct {

	/*
	  In: Body
	*/
	Payload models.Dummy `json:"body,omitempty"`
}

// NewPostUserLoginInternalServerError creates PostUserLoginInternalServerError with default headers values
func NewPostUserLoginInternalServerError() *PostUserLoginInternalServerError {

	return &PostUserLoginInternalServerError{}
}

// WithPayload adds the payload to the post user login internal server error response
func (o *PostUserLoginInternalServerError) WithPayload(payload models.Dummy) *PostUserLoginInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post user login internal server error response
func (o *PostUserLoginInternalServerError) SetPayload(payload models.Dummy) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUserLoginInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
