// Code generated by go-swagger; DO NOT EDIT.

package meeting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateMeetingHandlerFunc turns a function with the right signature into a create meeting handler
type CreateMeetingHandlerFunc func(CreateMeetingParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateMeetingHandlerFunc) Handle(params CreateMeetingParams) middleware.Responder {
	return fn(params)
}

// CreateMeetingHandler interface for that can handle valid create meeting params
type CreateMeetingHandler interface {
	Handle(CreateMeetingParams) middleware.Responder
}

// NewCreateMeeting creates a new http.Handler for the create meeting operation
func NewCreateMeeting(ctx *middleware.Context, handler CreateMeetingHandler) *CreateMeeting {
	return &CreateMeeting{Context: ctx, Handler: handler}
}

/*
	CreateMeeting swagger:route POST /meeting meeting createMeeting

Создать встречу
*/
type CreateMeeting struct {
	Context *middleware.Context
	Handler CreateMeetingHandler
}

func (o *CreateMeeting) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateMeetingParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
