// Code generated by go-swagger; DO NOT EDIT.

package meeting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/racoon-devel/calendar/internal/server/models"
)

// CreateMeetingCreatedCode is the HTTP code returned for type CreateMeetingCreated
const CreateMeetingCreatedCode int = 201

/*
CreateMeetingCreated Встреча создана

swagger:response createMeetingCreated
*/
type CreateMeetingCreated struct {

	/*
	  In: Body
	*/
	Payload *models.CreateMeetingResponse `json:"body,omitempty"`
}

// NewCreateMeetingCreated creates CreateMeetingCreated with default headers values
func NewCreateMeetingCreated() *CreateMeetingCreated {

	return &CreateMeetingCreated{}
}

// WithPayload adds the payload to the create meeting created response
func (o *CreateMeetingCreated) WithPayload(payload *models.CreateMeetingResponse) *CreateMeetingCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create meeting created response
func (o *CreateMeetingCreated) SetPayload(payload *models.CreateMeetingResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateMeetingCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateMeetingBadRequestCode is the HTTP code returned for type CreateMeetingBadRequest
const CreateMeetingBadRequestCode int = 400

/*
CreateMeetingBadRequest Неверные данные в запросе

swagger:response createMeetingBadRequest
*/
type CreateMeetingBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.CreateMeetingError `json:"body,omitempty"`
}

// NewCreateMeetingBadRequest creates CreateMeetingBadRequest with default headers values
func NewCreateMeetingBadRequest() *CreateMeetingBadRequest {

	return &CreateMeetingBadRequest{}
}

// WithPayload adds the payload to the create meeting bad request response
func (o *CreateMeetingBadRequest) WithPayload(payload *models.CreateMeetingError) *CreateMeetingBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create meeting bad request response
func (o *CreateMeetingBadRequest) SetPayload(payload *models.CreateMeetingError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateMeetingBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateMeetingUnauthorizedCode is the HTTP code returned for type CreateMeetingUnauthorized
const CreateMeetingUnauthorizedCode int = 401

/*
CreateMeetingUnauthorized Требуется авторизация

swagger:response createMeetingUnauthorized
*/
type CreateMeetingUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.CreateMeetingError `json:"body,omitempty"`
}

// NewCreateMeetingUnauthorized creates CreateMeetingUnauthorized with default headers values
func NewCreateMeetingUnauthorized() *CreateMeetingUnauthorized {

	return &CreateMeetingUnauthorized{}
}

// WithPayload adds the payload to the create meeting unauthorized response
func (o *CreateMeetingUnauthorized) WithPayload(payload *models.CreateMeetingError) *CreateMeetingUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create meeting unauthorized response
func (o *CreateMeetingUnauthorized) SetPayload(payload *models.CreateMeetingError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateMeetingUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateMeetingInternalServerErrorCode is the HTTP code returned for type CreateMeetingInternalServerError
const CreateMeetingInternalServerErrorCode int = 500

/*
CreateMeetingInternalServerError Ошибка на стороне сервера

swagger:response createMeetingInternalServerError
*/
type CreateMeetingInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.CreateMeetingError `json:"body,omitempty"`
}

// NewCreateMeetingInternalServerError creates CreateMeetingInternalServerError with default headers values
func NewCreateMeetingInternalServerError() *CreateMeetingInternalServerError {

	return &CreateMeetingInternalServerError{}
}

// WithPayload adds the payload to the create meeting internal server error response
func (o *CreateMeetingInternalServerError) WithPayload(payload *models.CreateMeetingError) *CreateMeetingInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create meeting internal server error response
func (o *CreateMeetingInternalServerError) SetPayload(payload *models.CreateMeetingError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateMeetingInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
