// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Calendar API
//
//	API for Calendar demo project
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
