swagger: '2.0'
info:
  version: 1.0.0
  title: Calendar API
  description: API for Calendar demo project

tags:
  - name: user
    description: Пользователь календаря
  - name: meeting
    description: Встреча

paths:
  /user:
    post:
      tags:
        - user
      summary: Создание пользователя
      description: Доступно без аутентификации, может вызываться при регистрации нового пользователя
      operationId: createUser
      parameters:
        - name: user
          in: body
          schema:
            $ref: "#/definitions/CreateUserRequest"

      responses:
        '201':
          description: OK
          schema:
            $ref: "#/definitions/CreateUserResponse"
        '400':
          description: Не удалось выполнить запрос (пользователь уже существует)
          schema:
            $ref: "#/definitions/Dummy"
        '500':
          description: Ошибка на стороне сервера
          schema:
            $ref: "#/definitions/Dummy"
    get:
      tags:
        - user
      summary: Получение списка всех пользователей
      description: Вернуть список имен и фамилий пользователей (требует авторизацию)
      responses:
        '200':
          description: Список пользователей (в идеале бы прикрутить поиск по имени и фамилии, но для простоты оставлю так)
          schema:
            $ref: "#/definitions/GetUsersResponse"

        '500':
          description: Ошибка на стороне сервера
          schema:
            $ref: "#/definitions/Dummy"
  /user/login:
    post:
      tags:
        - user
      summary: Вход в систему
      parameters:
        - name: credentials
          in: body
          schema:
            $ref: "#/definitions/LoginRequest"
      responses:
        '200':
          description: Вход выполнен успешно
          schema:
            $ref: "#/definitions/LoginResponse"
        '403':
          description: Доступ запрещен
          schema:
            $ref: "#/definitions/Dummy"
        '500':
          description: Ошибка на стороне сервера
          schema:
            $ref: "#/definitions/Dummy"

definitions:
  Dummy:
    type: object

  Login:
    type: string
    minLength: 1
    maxLength: 32
    description: Логин для входа в систему

  Password:
    type: string
    minLength: 8
    maxLength: 32
    description: Пароль

  CreateUserResponse:
    type: object
    required:
      - id
    additionalProperties: false
    properties:
      id:
        type: integer
        description: Идентификатор созданного пользователя
  CreateUserRequest:
    type: object
    additionalProperties: false
    required:
      - login
      - name
      - surname
      - password
    properties:
      login:
        $ref: "#/definitions/Login"
      name:
        type: string
        minLength: 1
        description: Имя пользователя
      surname:
        type: string
        minLength: 1
        description: Фамилия пользователя
      password:
        $ref: "#/definitions/Password"
  GetUsersResponse:
    type: object
    required:
      - users
    properties:
      users:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            surname:
              type: string

  LoginRequest:
    type: object
    required:
      - login
      - password
    properties:
      login:
        $ref: "#/definitions/Login"
      password:
        $ref: "#/definitions/Password"

  LoginResponse:
    type: object
    properties:
      access_token:
        type: string


